# Jekyll Configuration

# Website settings
title: "My Research Website"
description: "Doctoral Researcher in Energy & Environmental Economics"
theme: minima  # You can change this theme
baseurl: ""
url: "https://your-username.github.io"
github_username: your-username

# Navigation menu
collections:
  pages:
    output: true

# Permalinks
permalink: /:title/
