---
layout: default
title: Home
---

# Welcome to My Research Website

Hi, I'm **[Your Name]**, a PhD researcher specializing in **energy and environmental economics**. I use **Bayesian econometrics, big data methods, and statistical modeling** to analyze the relationship between **climate change and energy demand**.

## About Me
- **Affiliation:** Junior Researcher at CAU-Kiel, Institute of Environmental, Resource, and Spatial Economics
- **Skills:** Bayesian Multilevel Models, R, Python, Data Science
- **Research Interests:** Climate Change, Energy Economics, Sustainable Policy

## Recent Research
- **Bayesian Approaches in Energy Demand Forecasting**  
- **Impact of Climate Variability on Energy Consumption Trends**
- **Big Data Applications in Environmental Policy**

[View My Research](/research/)

---

## Contact
You can reach me via:  
📧 Email: [your email]  
💼 [LinkedIn Profile](#)  
📄 [Google Scholar](#)  

---

## How to Deploy This Website
1. **Fork & Clone** this repository on GitHub.
2. **Edit `_config.yml`** to update personal details.
3. **Commit & Push Changes** to publish updates.

For a **custom domain**, update the `CNAME` file with your domain name.

---

### **Additional Pages:**
- **[Research](/research/)**
- **[Publications](/publications/)**
- **[Contact](/contact/)**

This site is powered by **Jekyll & GitHub Pages**.
