title: "My Research Website"
description: "Doctoral Researcher in Energy & Environmental Economics"
theme: minima  # Or another Jekyll theme
baseurl: ""
url: "https://peerlasse.github.io"
github_username: PeerLasse


### **Additional Pages:**
- **[Research](/research/)**
- **[Publications](/publications/)**
- **[Contact](/contact/)**

This site is powered by **Jekyll & GitHub Pages**.
